version: '3.4'

services:
  adminer:
    image: adminer
  TodoManagementDB:
    container_name: TodoManagementDB
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: TodoManagementDB
    ports:
      - "5432:5432"
    volumes:
      - TodoManagementDB_data:/var/lib/postgresql/data
  todomanagementapi.app:
    image: ${DOCKER_REGISTRY-}todomanagementapiapp
    build:
      context: .
      dockerfile: TodoManagementAPI.App/Dockerfile

volumes:
  TodoManagementDB_data:
    external: false
